### ISSUE TITLE
App crashes when creating a habit with empty date

### ISSUE THREAD

**Issue by mbengert** [CMPUT301F21T43/CMPUT-301-Project#61]
When you leave the title or reason empty the app no longer crashes, but if you leave the date empty the app crashes and sends  you to the default account (ie. you get logged out somehow). This also happens when trying to confirm an empty habit event

Update: The issue has been fixed for Habit dates, but still persists for habit events currently (issue 64)

**Comment by marty-rudolf** [comment]
@mbengert can you edit this issue so that it's just for Habit date, then create a separate issue for the Habit Event. I have fixed the empty date so I can then close this issue.
